#ifndef ROBOT_CONTROLLER_VERSION_H
#define ROBOT_CONTROLLER_VERSION_H

#define ROBOT_CONTROLLER_FIRMWARE_VERSION_MAJOR 0
#define ROBOT_CONTROLLER_FIRMWARE_VERSION_MINOR 1
#define ROBOT_CONTROLLER_FIRMWARE_VERSION_PATCH 0

#define ROBOT_CONTROLLER_FIRMWARE_VERSION_STRING "0.1.0"
#define ROBOT_CONTROLLER_PROTOCOL_VERSION_STRING "0.1"
#define ROBOT_CONTROLLER_BOARD_NAME "stm32_robot_controller"
#define ROBOT_CONTROLLER_BUILD_CHANNEL "draft"

#endif /* ROBOT_CONTROLLER_VERSION_H */
